### ISSUE TITLE
issue with getting all pokemon 

### ISSUE THREAD

**Issue by asmitt8373** [danielguirra/pkmonjs#1]
<img width="1029" alt="Screen Shot 2022-09-22 at 9 36 46 PM" src="https://user-images.githubusercontent.com/107019893/191892917-0b74ee81-ece5-4b7c-b82a-744aa94f1111.png">

**Comment by danielguirra** [comment]
Hello, I hope you are well, sorry for the inconvenience it was solved in the new update 1.2.12
