### ISSUE TITLE
Incorrect gender ratio

### ISSUE THREAD

**Issue by DarkVillager** [danielguirra/pkmonjs#4]
**Describe the bug**
Incorrect gender ratio for e.g. Sobble

**To Reproduce**
1. Use pkmonjs to get a pokemon e.g. Sobble
2. View gender ratio
3. See it’s not correct (100% male, instead of 87.5% male & 12.5% female)

**Expected behavior**

**Screenshots**
![IMG_3947](https://github.com/danielguirra/pkmonjs/assets/42322979/0573b83e-2141-4bbe-aca8-b48ea3761bdc)
![IMG_3946](https://github.com/danielguirra/pkmonjs/assets/42322979/866382bc-28c4-4a98-97c3-fe59f7683890)

**Comment by danielguirra** [comment]
Hello thanks for the inconsistent data warning, I will solve the problem as soon as possible

**Comment by DarkVillager** [comment]
> Hello thanks for the inconsistent data warning, I will solve the problem as soon as possible.
> 
> This error occurs due to wrong information from the "pokeapi.co" api, while it is wrong there I cannot solve it because it would break all the other pokemons' genre, maybe I'll have to use the bulbapedia database.

We could open an issue on [their github](https://github.com/PokeAPI/pokedex/issues)

**Comment by danielguirra** [comment]
It will not be necessary to research about it and I discovered that with the 9th generation it changed how the logic of genres worked, I adapted the code and launched a new version.

```
npm remove pkmonjs
```

````bash
npm install pkmonjs@1.4.0
````

**Comment by DarkVillager** [comment]
> It will not be necessary to research about it and I discovered that with the 9th generation it changed how the logic of genres worked, I adapted the code and launched a new version.
> 
> ```
> npm remove pkmonjs
> ```
> 
> ```shell
> npm install pkmonjs@1.4.0
> ```
Still incorrect, but I fixed it with my pr #7 
![image](https://github.com/danielguirra/pkmonjs/assets/42322979/e36d16f3-ab34-44c0-8e9d-1c0b51427eaf)

**Comment by danielguirra** [comment]
Thanks I will merge and generate a new version, feel free to write about the project

**Comment by DarkVillager** [comment]
> Thanks I will merge and generate a new version, feel free to write about the project.
> 
> edit:
> 
> ```shell
> npm i pkmonjs@1.5.0
> ```

I will add a footer to my bot, so people will get to know the project.

**Comment by danielguirra** [comment]
> > Thanks I will merge and generate a new version, feel free to write about the project.
> > edit:
> > ```shell
> > npm i pkmonjs@1.5.0
> > ```
> 
> I will add a footer to my bot, so people will get to know the project.

Thks

**Comment by DarkVillager** [comment]
> Thanks I will merge and generate a new version, feel free to write about the project.
> 
> edit:
> 
> ```shell
> npm i pkmonjs@1.5.0
> ```
Perfect!
![image](https://github.com/danielguirra/pkmonjs/assets/42322979/9879e33e-89ce-44d0-a80a-4c81d32b3283)
